repos:
  - repo: local
    hooks:
      - id: ruff
        name: Ruff Linter
        entry: ruff
        language: system
        types: [ python ]
        files: ^app/

#      - id: yarn-lint
#        name: Yarn Lint
#        entry: yarn --cwd ./frontend/factory lint
#        language: system
#        files: ^frontend/factory/.*\.(js|jsx|ts|tsx)$